services:
  backend:
    # image: backend:latest
    container_name: backend
    restart: always
    ports:
      - $LOCAL_SERVER_PORT:$SERVER_PORT
      - $LOCAL_DEBUG_PORT:$CONTAINER_DEBUG_PORT
    env_file:
      - ./.env

    build:
      context: .
      dockerfile: Dockerfile
    #   environment:
    #     - SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
    #     - SPRING_DATASOURCE_USERNAME: "$SPRING_DATASOURCE_USERNAME"
    #     - SPRING_DATASOURCE_PASSWORD: "$SPRING_DATASOURCE_PASSWORD"
    # environment:
    #   - SPRING_DATASOURCE_URL: $SPRING_DATASOURCE_URL
    #   - SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
    #   - SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    # - SPRING_DATASOURCE_DRIVER_CLASS_NAME: $SPRING_DATASOURCE_DRIVER_CLASS_NAME
    # - SPRING_JPA_HIBERNATE_DDL_AUTO: $SPRING_JPA_HIBERNATE_DDL_AUTO
    # - SPRING_JPA_SHOW_SQL: $SPRING_JPA_SHOW_SQL
    # - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: $SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
    # - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: $SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
    # - SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: $SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS
    depends_on:
      - mysql_db
    networks:
      - database_network
  mysql_db:
    image: mysql:9.2
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - database_network
volumes:
  mysql_data:
networks:
  database_network:
    driver: bridge
